"""update_audit_logs_schema

Revision ID: 5116bd1fb705
Revises: fe5d34a30d7c
Create Date: 2025-12-12 00:41:26.615981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5116bd1fb705'
down_revision = 'fe5d34a30d7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_oauth_providers_email'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_provider_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('ix_oauth_providers_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.BigInteger(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_email', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_ip', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('http_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('http_path', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('http_status', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('audit_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('attempt', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_status_created', 'audit_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_shop_id'), 'audit_logs', ['shop_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_user_id'], ['id'])
    op.drop_column('audit_logs', 'actor_type')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'diff')
    op.drop_column('audit_logs', 'idempotency_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('actor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('actor_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_shop_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_tenant_created', table_name='audit_logs')
    op.drop_index('idx_audit_status_created', table_name='audit_logs')
    op.drop_index('idx_audit_actor_created', table_name='audit_logs')
    op.drop_index('idx_audit_action_created', table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('audit_logs', 'attempt')
    op.drop_column('audit_logs', 'response_metadata')
    op.drop_column('audit_logs', 'request_metadata')
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'http_status')
    op.drop_column('audit_logs', 'http_path')
    op.drop_column('audit_logs', 'http_method')
    op.drop_column('audit_logs', 'actor_ip')
    op.drop_column('audit_logs', 'actor_email')
    op.drop_column('audit_logs', 'actor_user_id')
    op.create_table('oauth_providers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_providers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_providers_pkey'))
    )
    op.create_index(op.f('ix_oauth_providers_id'), 'oauth_providers', ['id'], unique=False)
    op.create_index(op.f('idx_oauth_providers_user_id'), 'oauth_providers', ['user_id'], unique=False)
    op.create_index(op.f('idx_oauth_providers_provider_user_id'), 'oauth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_index(op.f('idx_oauth_providers_email'), 'oauth_providers', ['email'], unique=False)
    # ### end Alembic commands ###
