"""add_policy_enforcement_fields

Revision ID: f9713cb3c87f
Revises: 5116bd1fb705
Create Date: 2025-12-12 01:33:59.765544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9713cb3c87f'
down_revision = '5116bd1fb705'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_oauth_providers_email'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_provider_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('ix_oauth_providers_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.add_column('ai_generations', sa.Column('can_publish', sa.Integer(), nullable=True))
    op.add_column('listing_jobs', sa.Column('policy_status', sa.String(length=20), nullable=True))
    op.add_column('listing_jobs', sa.Column('policy_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listing_jobs', sa.Column('policy_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listing_jobs', sa.Column('policy_block_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_jobs', 'policy_block_reason')
    op.drop_column('listing_jobs', 'policy_checked_at')
    op.drop_column('listing_jobs', 'policy_flags')
    op.drop_column('listing_jobs', 'policy_status')
    op.drop_column('ai_generations', 'can_publish')
    op.create_table('oauth_providers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_providers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_providers_pkey'))
    )
    op.create_index(op.f('ix_oauth_providers_id'), 'oauth_providers', ['id'], unique=False)
    op.create_index(op.f('idx_oauth_providers_user_id'), 'oauth_providers', ['user_id'], unique=False)
    op.create_index(op.f('idx_oauth_providers_provider_user_id'), 'oauth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_index(op.f('idx_oauth_providers_email'), 'oauth_providers', ['email'], unique=False)
    # ### end Alembic commands ###
