"""add_audit_logs_table

Revision ID: fe5d34a30d7c
Revises: 20251211220000
Create Date: 2025-12-11 23:18:56.669008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe5d34a30d7c'
down_revision = '20251211220000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_oauth_providers_email'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_provider_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('idx_oauth_providers_user_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.add_column('ai_generations', sa.Column('policy_status', sa.String(length=20), nullable=True))
    op.add_column('ai_generations', sa.Column('policy_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_generations', sa.Column('reviewed_by', sa.BigInteger(), nullable=True))
    op.add_column('ai_generations', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_generations', sa.Column('review_decision', sa.String(length=20), nullable=True))
    op.add_column('ai_generations', sa.Column('provider', sa.String(length=20), nullable=True))
    op.add_column('ai_generations', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('ai_generations', sa.Column('generation_time_ms', sa.Integer(), nullable=True))
    op.alter_column('ai_generations', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ai_generations', 'prompt_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('ai_generations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ai_generations', 'cost_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_generations', 'cost_usd_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_ai_gen_product'), table_name='ai_generations')
    op.drop_index(op.f('idx_ai_gen_status'), table_name='ai_generations')
    op.drop_index(op.f('idx_ai_gen_tenant'), table_name='ai_generations')
    op.create_foreign_key(None, 'ai_generations', 'users', ['reviewed_by'], ['id'])
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_tenant_time'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.create_foreign_key(None, 'audit_logs', 'shops', ['shop_id'], ['id'])
    op.add_column('listing_jobs', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('listing_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('listing_jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('listing_jobs', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listing_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listing_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('listing_jobs', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('listing_jobs', 'error_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listing_jobs', 'etsy_listing_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('listing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('listing_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_listing_jobs_shop_state'), table_name='listing_jobs')
    op.drop_index(op.f('idx_listing_jobs_tenant'), table_name='listing_jobs')
    op.drop_index(op.f('ix_listing_jobs_idempotency_key'), table_name='listing_jobs')
    op.create_unique_constraint(None, 'listing_jobs', ['idempotency_key'])
    op.drop_column('listing_jobs', 'attempts')
    op.drop_column('listing_jobs', 'state')
    op.alter_column('oauth_tokens', 'refresh_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('orders', sa.Column('supplier_order_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('orders', 'etsy_receipt_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_orders_shop'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_etsy_receipt_id'), table_name='orders')
    op.create_unique_constraint(None, 'orders', ['etsy_receipt_id'])
    op.drop_column('orders', 'printful_order_id')
    op.alter_column('products', 'source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('products', 'ingest_batch_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_products_batch'), table_name='products')
    op.drop_index(op.f('idx_products_tags_gin'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('idx_products_tenant'), table_name='products')
    op.add_column('schedules', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('schedules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('schedules', sa.Column('weekly_quota', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('daily_used', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('weekly_used', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('last_weekly_reset', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('schedules', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('execution_count', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('total_success', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('total_failed', sa.Integer(), nullable=True))
    op.alter_column('schedules', 'shop_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('schedules', 'cron_expr',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('schedules', 'daily_quota',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_schedules_active'), table_name='schedules')
    op.drop_index(op.f('idx_schedules_shop'), table_name='schedules')
    op.create_index('idx_schedules_next_run_enabled', 'schedules', ['next_run_at', 'status'], unique=False)
    op.create_index('idx_schedules_shop_status', 'schedules', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_shop_id'), 'schedules', ['shop_id'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.drop_column('schedules', 'active')
    op.alter_column('usage_costs', 'ai_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usage_costs', 'ai_cost_usd_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usage_costs', 'storage_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('idx_usage_tenant_date'), table_name='usage_costs')
    op.drop_index(op.f('idx_users_email_verified'), table_name='users')
    op.drop_index(op.f('idx_users_reset_token'), table_name='users')
    op.drop_index(op.f('idx_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider_user_id'), table_name='users')
    op.drop_constraint(op.f('users_reset_token_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_verification_token_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.alter_column('webhook_events', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('webhook_events', 'external_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('webhook_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('idx_webhook_provider'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_id'), table_name='webhook_events')
    op.create_unique_constraint(None, 'webhook_events', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_events', type_='unique')
    op.create_index(op.f('ix_webhook_events_external_id'), 'webhook_events', ['external_id'], unique=True)
    op.create_index(op.f('idx_webhook_status'), 'webhook_events', ['status'], unique=False)
    op.create_index(op.f('idx_webhook_provider'), 'webhook_events', ['provider'], unique=False)
    op.alter_column('webhook_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('webhook_events', 'external_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('webhook_events', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.create_unique_constraint(op.f('users_verification_token_key'), 'users', ['verification_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_reset_token_key'), 'users', ['reset_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_oauth_provider_user_id'), 'users', ['oauth_provider', 'oauth_provider_user_id'], unique=False)
    op.create_index(op.f('idx_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_index(op.f('idx_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('idx_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('idx_usage_tenant_date'), 'usage_costs', ['tenant_id', 'date'], unique=False)
    op.alter_column('usage_costs', 'storage_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('usage_costs', 'ai_cost_usd_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_costs', 'ai_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('schedules', sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_shop_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_index('idx_schedules_shop_status', table_name='schedules')
    op.drop_index('idx_schedules_next_run_enabled', table_name='schedules')
    op.create_index(op.f('idx_schedules_shop'), 'schedules', ['shop_id'], unique=False)
    op.create_index(op.f('idx_schedules_active'), 'schedules', ['active'], unique=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('schedules', 'daily_quota',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'cron_expr',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('schedules', 'shop_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('schedules', 'total_failed')
    op.drop_column('schedules', 'total_success')
    op.drop_column('schedules', 'execution_count')
    op.drop_column('schedules', 'last_error')
    op.drop_column('schedules', 'next_run_at')
    op.drop_column('schedules', 'last_run_at')
    op.drop_column('schedules', 'status')
    op.drop_column('schedules', 'last_weekly_reset')
    op.drop_column('schedules', 'last_daily_reset')
    op.drop_column('schedules', 'weekly_used')
    op.drop_column('schedules', 'daily_used')
    op.drop_column('schedules', 'weekly_quota')
    op.drop_column('schedules', 'type')
    op.drop_column('schedules', 'description')
    op.drop_column('schedules', 'name')
    op.create_index(op.f('idx_products_tenant'), 'products', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_products_tags_gin'), 'products', ['tags_raw'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_batch'), 'products', ['ingest_batch_id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('products', 'ingest_batch_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('orders', sa.Column('printful_order_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='unique')
    op.create_index(op.f('ix_orders_etsy_receipt_id'), 'orders', ['etsy_receipt_id'], unique=True)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_shop'), 'orders', ['shop_id'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('orders', 'etsy_receipt_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('orders', 'order_data')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'supplier_order_id')
    op.alter_column('oauth_tokens', 'refresh_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('listing_jobs', sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('listing_jobs', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listing_jobs', type_='unique')
    op.create_index(op.f('ix_listing_jobs_idempotency_key'), 'listing_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('idx_listing_jobs_tenant'), 'listing_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_listing_jobs_shop_state'), 'listing_jobs', ['shop_id', 'state'], unique=False)
    op.alter_column('listing_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('listing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('listing_jobs', 'etsy_listing_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listing_jobs', 'error_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listing_jobs', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('listing_jobs', 'completed_at')
    op.drop_column('listing_jobs', 'started_at')
    op.drop_column('listing_jobs', 'scheduled_for')
    op.drop_column('listing_jobs', 'retry_count')
    op.drop_column('listing_jobs', 'error_message')
    op.drop_column('listing_jobs', 'status')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('idx_audit_tenant_time'), 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('audit_logs', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'ai_generations', type_='foreignkey')
    op.create_index(op.f('idx_ai_gen_tenant'), 'ai_generations', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_ai_gen_status'), 'ai_generations', ['status'], unique=False)
    op.create_index(op.f('idx_ai_gen_product'), 'ai_generations', ['product_id'], unique=False)
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ai_generations', 'cost_usd_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_generations', 'cost_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_generations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ai_generations', 'prompt_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_generations', 'model',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ai_generations', 'generation_time_ms')
    op.drop_column('ai_generations', 'tokens_used')
    op.drop_column('ai_generations', 'provider')
    op.drop_column('ai_generations', 'review_decision')
    op.drop_column('ai_generations', 'reviewed_at')
    op.drop_column('ai_generations', 'reviewed_by')
    op.drop_column('ai_generations', 'policy_checked_at')
    op.drop_column('ai_generations', 'policy_status')
    op.create_table('oauth_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_providers_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_providers_pkey'))
    )
    op.create_index(op.f('idx_oauth_providers_user_id'), 'oauth_providers', ['user_id'], unique=False)
    op.create_index(op.f('idx_oauth_providers_provider_user_id'), 'oauth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_index(op.f('idx_oauth_providers_email'), 'oauth_providers', ['email'], unique=False)
    # ### end Alembic commands ###
